In [35]:
import numpy as np

claculate determinant

In [30]:
class Determinant:
    def get_minor(self, matrix, i, j):
        return [row[:j] + row[j+1:] for row in (matrix[:i] + matrix[i+1:])]

    def calculate_determinant(self, matrix):
        # Base case for a 2x2 matrix
        if len(matrix) == 2:
            return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
        
        
        det = 0
        for c in range(len(matrix)):
            det += ((-1) ** c) * matrix[0][c] * self.calculate_determinant(self.get_minor(matrix, 0, c))
        return det
        
det = Determinant()
matrix = [[2,3],
          [5,6,]]
det.calculate_determinant(matrix)

-3

In [33]:
def gauss_jordan(matrix):
    
    n  = len(matrix)
    
    if det.calculate_determinant(matrix) == 0:
        return "can't calculate inverse of a singular matrix!"
    
    aug_matrix = np.hstack((matrix , np.identity(n))) # we can use np.eye(n) to create identity matrix
    
    for i in range(n):
        diag_element = aug_matrix[i][i]
        
        aug_matrix[i] = aug_matrix[i] / diag_element # making diagonal element = 1
        
        for j in range(n): # make other element of that column = 0
            if i!=j:
                factor = aug_matrix[j][i]
                aug_matrix[j] = aug_matrix[j] - factor*aug_matrix[i]
                
    inverse_matrix = aug_matrix[: , n:]
    return inverse_matrix

matrix = np.array([[2,1],[4,2]],dtype=float)
gauss_jordan(matrix)

"can't calculate inverse of a singular matrix!"

In [3]:
np.linalg.inv(matrix) # numpy in-built function

array([[ 7., -3.],
       [-2.,  1.]])

In [36]:
vector = np.random.rand(4,3,2,4)

print(vector)
vector.ndim


[[[[0.98441937 0.40438891 0.52195827 0.66977095]
   [0.17493456 0.3428051  0.39105091 0.28027807]]

  [[0.03034944 0.98653384 0.42507061 0.68859697]
   [0.48238038 0.7220193  0.96931148 0.82415704]]

  [[0.14601972 0.6616888  0.18882224 0.43273744]
   [0.12288774 0.59405901 0.16792645 0.21833305]]]


 [[[0.26907835 0.89947576 0.38301841 0.86272375]
   [0.16330275 0.40006395 0.57288856 0.6611778 ]]

  [[0.63569146 0.77703658 0.1594006  0.46749052]
   [0.5193908  0.35721148 0.43085846 0.13953637]]

  [[0.58253115 0.87405124 0.23032435 0.15351349]
   [0.89535942 0.88318082 0.00431131 0.91565465]]]


 [[[0.35128583 0.00237243 0.50878668 0.72700661]
   [0.71505238 0.36772442 0.27067742 0.82776077]]

  [[0.46156829 0.05668836 0.4460453  0.04484068]
   [0.33929661 0.4455657  0.97235361 0.38655363]]

  [[0.65839063 0.46044043 0.09499766 0.54471818]
   [0.2827353  0.14094666 0.87471216 0.23440565]]]


 [[[0.00436622 0.54411177 0.11156104 0.48004458]
   [0.94343615 0.5920679  0.60349074 0.393619

4

In [37]:
q = vector[np.newaxis,:,:]
q.shape

(1, 4, 3, 2, 4)

In [34]:
m = np.arange(2,11).reshape(3,3)

det = np.linalg.det(m)

print(det)

0.0
