In [1]:
import numpy as np
# require less memory
# faster
# convinient

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [44]:
df = '/home/balerion/Desktop/leetcode_Ai/Ai/Andrew-NG-Notes/Machine Learning notebooks By Andrew NG/ex1/data/ex1data1.txt'
cols = np.loadtxt(df , delimiter=',',usecols=(0,1),unpack=True)

X = np.transpose(np.array(cols[:-1]))
y = np.transpose(np.array(cols[-1:]))

X = np.insert(X,0,1,axis = 1) # axis = 1 -> row and 0 for column
# print(X[:,1])

print(X.shape[0]) # -> number of rows
print(X.shape[1]) # -> number of columns
print(X.shape)

print(X.ndim)
print(X.itemsize) # -> float64 -> 8 bytes
print(X.dtype)
print(X.size)

97
2
(97, 2)
2
8
float64
194


In [43]:
a = np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float64)
print(a)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [65]:
print(np.zeros((2,4),dtype=np.int32))
print(np.ones((2,2,2)))
print(np.arange(1,5,.2))
print(np.linspace(1,5,5,endpoint=False,retstep=True)) # when endpoint set to false retstep changes

[[0 0 0 0]
 [0 0 0 0]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]
(array([1. , 1.8, 2.6, 3.4, 4.2]), 0.8)


In [81]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape)

arr.reshape(2,2,2)

arr.ravel() #flatten

arr.flatten() #flatten

arr.min(axis=0) # arr.max()

arr.sum(axis = 1) 
arr.prod()
np.sqrt(arr) # generic function
np.std(arr) # standard deviation


(2, 4)


2.29128784747792

In [86]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

a+b
a/b
print(a*b)
print(np.dot(a,b))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [93]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

x[:,3] # -> accessing columns
x[2,:] # -> accessing rows

array([ 9, 10, 11, 12])

In [95]:
m = np.arange(1,7).reshape(3,2)

n = np.arange(7,13).reshape(3,2)

In [96]:
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
n

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [98]:
np.vstack((m,n))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [99]:
np.hstack((m,n))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [101]:
array = np.arange(30).reshape(2,15)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [102]:
np.hsplit(array,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [104]:
np.vsplit(array,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [106]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
o = z >= 4
o

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [110]:
z[o] # return numbers where value is true

array([4, 5, 6, 7, 8])

In [115]:
z[o] = -1
z

array([[ 0,  1,  2],
       [ 3, -1, -1],
       [-1, -1, -1]])

In [17]:
arr1 = np.ones((5,5,1))
arr2 = np.identity(5)

arr3 = arr2[:,:,np.newaxis]

arr3.shape

# a = np.hstack((arr1 , arr3))
# print(a)

(5, 5, 1)