# *Understading basics*

In [1]:
import numpy as np
import math

In [4]:
print(np.linalg.norm((4,5))) # magnitude of a vector
print(np.sqrt((16+25)))

6.4031242374328485
6.4031242374328485


In [10]:
#unit vector
def unit_vec(vec):
    return vec / np.linalg.norm(vec)

print(unit_vec((4,5)))
print(unit_vec((40,50)))

#magnitude of unit vector

print(np.linalg.norm((0.62469505, 0.78086881)))


[0.62469505 0.78086881]
[0.62469505 0.78086881]
1.0000000019626591


In [11]:
# calculating dot product
def dot_prod(x,y,theta):
    x_norm = np.linalg.norm(x)
    y_norm = np.linalg.norm(y)
    return x_norm*y_norm*np.cos(np.radians(theta))

dot_prod(4,5,0)


20.0

In [12]:
def example_functional_margin(w, b, x, y):
    result = y * (np.dot(w, x) + b)
    return result 

there is a major problem with the functional margin: is not scale invariant.

In [13]:
x = np.array([1, 1]) 
y = 1 
 
b_1 = 5 
w_1 = np.array([2, 1]) 
 
w_2 = w_1 * 10 
b_2 = b_1 * 10 
 
print(example_functional_margin(w_1, b_1, x, y))  # 8 
print(example_functional_margin(w_2, b_2, x, y))  # 80 

8
80


In [14]:
# Compute the geometric margin of an example (x,y) 
# with respect to a hyperplane defined by w and b. 
def example_geometric_margin(w, b, x, y):
    norm = np.linalg.norm(w)
    result = y * (np.dot(w/norm, x) + b/norm)
    return result 

In [15]:
x = np.array([1, 1]) 
y = 1 
 
b_1 = 5 
w_1 = np.array([2, 1]) 
 
w_2 = w_1 * 10 
b_2 = b_1 * 10 
 
print(example_geometric_margin(w_1, b_1, x, y)) 
print(example_geometric_margin(w_2, b_2, x, y))  

3.577708763999664
3.577708763999664


### *Functional margin*

*The functional margin measures how well an example is classified and how confident the classifier is about the classification*

*It is used during the training process to ensure that the margin between the support vectors (data points that are closest to the decision boundary) and the decision boundary is maximized. In mathematical formulations, the functional margin is directly involved in the constraints of the optimization problem*


### *Geometric margin*

*The geometric margin provides a scale-invariant measure of how far an example is from the decision boundary. It represents the true margin of separation between the classes.*

*The goal of the SVM optimization process is to maximize the geometric margin. This is because the geometric margin is invariant to the scaling of w, making it a more meaningful measure of the classifier's robustness.*

In [8]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

b = np.linspace(-1, 2, 4)
print(b)

x = np.outer(a,b)

print(x)


[1 2 3 4]
[-1.  0.  1.  2.]
[[-1.  0.  1.  2.]
 [-2.  0.  2.  4.]
 [-3.  0.  3.  6.]
 [-4.  0.  4.  8.]]
